language: python
python:
  #- "2.5"
  #- "2.6"
  - "2.7"
  #- "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install poppler-utils  # For pdftohtml
#install:
  #- pip install -r requirements.txt --use-mirrors
# command to run tests
script: python setup.py test
